### ISSUE TITLE
LSP3IssuedAssets[] uses valueContent instead of elementValueContent

### ISSUE THREAD

**Issue by Hugoo** [lukso-network/LIPs#24]
The current JSON schema for `LSP3IssuedAssets[]` [source](https://github.com/lukso-network/LIPs/blob/master/LSPs/LSP-3-UniversalProfile.md#lsp3issuedassets) seems wrong: `valueContent` is used instead of `elementValueContent` (same issue for `type`).

```json
{
    "name": "LSP3IssuedAssets[]",
    "key": "0x3a47ab5bd3a594c3a8995f8fa58d0876c96819ca4516bd76100c92462f2f9dc0",
    "keyType": "Array",
    "valueContent": "Address",
    "valueType": "address"
}
```

I believe it should look similar to `LSP4Creators[]` instead:

```json
{
    "name": "LSP4Creators[]",
    "key": "0x114bd03b3a46d48759680d81ebb2b414fda7d030a7105a851867accf1c2352e7",
    "keyType": "Array",
    "valueContent": "Number",
    "valueType": "uint256",
    "elementValueContent": "Address",
    "elementValueType": "address"
}
```

## Suggested changes:

```json
{
    "name": "LSP3IssuedAssets[]",
    "key": "0x3a47ab5bd3a594c3a8995f8fa58d0876c96819ca4516bd76100c92462f2f9dc0",
    "keyType": "Array",
    "valueContent": "Number",
    "valueType": "uint256",
    "elementValueContent": "Address",
    "elementValueType": "address"
}
```

The above example is also used in the [ERC725YJSONSchema Array](https://github.com/lukso-network/LIPs/blob/master/LSPs/LSP-2-ERC725YJSONSchema.md#array) definition; I think it should be updated accordingly.

I will open a PR with a fix

**Comment by CJ42** [comment]
@Hugoo `elementValueType` and `elementValueContent` have been removed from the LSP2 Schema.
See PR #20 or this link: https://github.com/lukso-network/LIPs/pull/20/files

**Comment by Hugoo** [comment]
Yep indeed - back then it was unclear. We can close.
