### ISSUE TITLE
Icon Request: icon-lyx

### ISSUE THREAD

**Issue by CHEYCKIT** [lukso-network/LIPs#296]
Would like to to propose an official currency symbol to Lukso that would act as a shortened version for `LYX` and for `LUKSO`.

`⏣` this is the symbol we should use for `LUKSO`, 
`𝕃` would be the alternate symbol for `LYX`

I think the [Benzene](https://en.wikipedia.org/wiki/Benzene) `⏣` works in some scenarios rather well when the page is zoomed however in other cases, when the page is small, an alternate symbol would improve readability drastically, `𝕃` is the community's choice (we've went ahead and used it in https://wandz.works/lend), as repeating `LYX` too much all over dapp pages clutters the feed

Use cases would be same as ETH `Ξ` :

- IoT
- DApps
- Websites
- UI/UX

Integration in FontAwesome would look like this:
Build on `<i class="fa fa-lukso" aria-hidden="true"></i>` for ⏣
Build on `<i class="fa fa-lyx" aria-hidden="true"></i>` for 𝕃

Icon:
![image](https://github.com/lukso-network/LIPs/assets/126706593/46c1cd2e-eb9f-4b72-bf44-b3cee8f76564)
![image](https://github.com/lukso-network/LIPs/assets/126706593/060b18c0-212f-4c3b-b19a-040c6be79084)

[Unicode U+23E3](https://www.compart.com/en/unicode/U+23E3), HTML entity code `&#9187`
[Unicode U+1D543](https://www.compart.com/en/unicode/U+1D543), HTML entity code `&Lopf`

**Comment by frozeman** [comment]
This is a nice idea. We should get a bit more attention to community on this

**Comment by oukira27** [comment]
⏣ (U+23E3)
or
ㆨ (U+31A8)

First one is cool, second one is more with L + Y + X

**Comment by oukira27** [comment]
> Would like to to propose an official currency symbol to Lukso that would act as a shortened version for `LYX`.
> 
> `Ŀ` this is the symbol we should use. I initially wanted to use one of the 3 the hexagons in unicode (⬣) but they are hard to read on small screens and for near-sighted people (like me lol) so they'll often look like circles.
> 
> I think the [Latin Extended A](https://en.wikipedia.org/wiki/Latin_Extended-A) `Ŀ` works rather well (we've went ahead and used it in https://wandz.works/orderbooks, as repeating `LYX` too much all over the website was cluttering the pages)
> 
> Use cases would be same as ETH `Ξ` :
> 
> * IoT
> * DApps
> * Websites
> * UI/UX
> 
> Build on `<i class="fa fa-lyx" aria-hidden="true"></i>`
> 
> Icon: ![image](https://private-user-images.githubusercontent.com/126706593/340042901-6648222d-68ba-4f26-88de-a47b96511a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDgyNzIsIm5iZiI6MTcxODcwNzk3MiwicGF0aCI6Ii8xMjY3MDY1OTMvMzQwMDQyOTAxLTY2NDgyMjJkLTY4YmEtNGYyNi04OGRlLWE0N2I5NjUxMWE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDUyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWMyYjg4NzM2ODJkMGRiZWQyNDNiYjNhOTBjNDJjZmIyM2I4ZThkMzc4MWMwMWQxODBhYjc5ODk2NDhiZmVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6zdW57CoCGAbqCqXnZNh_2qitX6ir3r8wLLD8du89I)
> 
> [Unicode U+013F](https://charbase.com/013f-unicode-latin-capital-letter-l-with-middle-dot), HTML entity code `&Lmidot`
> 
> Made a poll on X: https://x.com/DWOPEs/status/1802855710205607984

⏣ (U+23E3)
or
ㆨ (U+31A8)

First one is really cool, second one is with a combo of L + Y + X

**Comment by CHEYCKIT** [comment]
> ⏣ (U+23E3) or ㆨ (U+31A8)
> 
> First one is cool, second one is more with L + Y + X

1st one will have to pass 
![image](https://github.com/lukso-network/LIPs/assets/126706593/8de2a5c2-c92b-423e-a78d-bb62b95d358a)

2nd one is nice but has formatting issues since it's japanese character
![image](https://github.com/lukso-network/LIPs/assets/126706593/37ef5fff-e19f-4ce8-ad58-59e19099fdee)

So far those are the only contender valid imo, we can make a new poll for these two later on @frozeman 

100 Ŀ
100 Ÿ

**Comment by CHEYCKIT** [comment]
> Would like to to propose an official currency symbol to Lukso that would act as a shortened version for `LYX`.
> 
> `⏣` this is the symbol we should use.
> 
> I think the [Latin Extended A](https://en.wikipedia.org/wiki/Benzene) `⏣` works rather well (we've went ahead and used it in https://wandz.works/orderbooks, as repeating `LYX` too much all over the website was cluttering the pages)
> 
> Use cases would be same as ETH `Ξ` :
> 
> * IoT
> * DApps
> * Websites
> * UI/UX
> 
> Build on `<i class="fa fa-lyx" aria-hidden="true"></i>`
> 
> Icon: ![image](https://private-user-images.githubusercontent.com/126706593/340774756-46c1cd2e-eb9f-4b72-bf44-b3cee8f76564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzI0MzgsIm5iZiI6MTcxODczMjEzOCwicGF0aCI6Ii8xMjY3MDY1OTMvMzQwNzc0NzU2LTQ2YzFjZDJlLWViOWYtNGI3Mi1iZjQ0LWIzY2VlOGY3NjU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNzM1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTNmNzViZjY4YTk0Y2VkMmYxNWVmZmEwZjU0N2MzN2YzYmEzNzk5OWViMjYxNDNmZmEwOGI4YmVlNDhmYmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.11Jx3tgebz7X-Wcj6mrogmBq_r3l9UbSomOrxNydDaA)
> 
> [Unicode U+23E3](https://www.compart.com/en/unicode/U+23E3), HTML entity code `&#9187`
> 
> Final Poll is here on X: https://x.com/DWOPEs/status/1803086212455936460?t=tJXqtJZZHIDB_Qiija6IEg&s=19

Edited to reflect the results of the poll. It'll be the benzene ring

**Comment by CHEYCKIT** [comment]
@frozeman the community wants ⏣ after a vote (i think it's too close to SOL (◎) i personally would still keep Ŀ, can you make the final call?

**Comment by oukira27** [comment]
Community is the way, it's not a centralized project decided by 1-2 person, if there is nothing more than tastes and colors, it owes to community right ?

> @frozeman the community wants ⏣ after a vote (i think it's too close to SOL (◎) i personally would still keep Ŀ, can you make the final call?

**Comment by CHEYCKIT** [comment]
> Community is the way, it's not a centralized project decided by 1-2 person, if there is nothing more than tastes and colors, it owes to community right ?

There is more than taste and colors though, if the symbol can be mistaken easily with another, it's fundamental problem for Dapps

**Comment by oukira27** [comment]
Ok so my opinion is that Ŀ is even worst and a bad idea, it's the marketing logo of Linea ^^ at least the ring is just text, and doesn't définie marketing usage like Ŀ is used by linea

**Comment by CHEYCKIT** [comment]
Option 1
Ŀ = Linea Marketing with no token
Ŀ = LUKSO Dapps

Option 2
⏣ = LUKSO Dapps
◎ = SOL Dapps

> Ok so my opinion is that Ŀ is even worst and a bad idea, it's the marketing logo of Linea ^^ at least the ring is just text, and doesn't define marketing usage like Ŀ is used by linea

How is option 2 better than option 1? Please explain

**Comment by oukira27** [comment]
Tbh Solana one is far from being the same than our ring, more bigger, better recognizable, i'm not that shocked, while Linea is exact copy of marketing, I really don't like

**Comment by CHEYCKIT** [comment]
> Tbh Solana one is far from being the same than our ring, more bigger and rounder, while our logo is better recognizable, i'm not that shocked, while Linea is exact copy of marketing, I really don't like

![Screenshot_20240619-131026_Kiwi_Browser (1).jpg](https://github.com/lukso-network/LIPs/assets/126706593/f666c174-3e7f-40f1-8779-4a7a831fe400)

Am I using SOL ticker here or the LYX Benzene (trick question)

Please use a zoom to answer this

**Comment by CHEYCKIT** [comment]
@oukira27 how about θ (Theta)? as in 

100 LYX  = 100 θ

Thoughts?

**Comment by oukira27** [comment]
> @oukira27 how about θ (Theta) or 𝕃 ? as in
> 
> 100 LYX = 100 θ 100 LYX = 100 𝕃
> 
> Thoughts?

I think  𝕃 is a good idea yeah ! Does it works well for dev side by using this one ? True it should be compatible for builders first, you're right

**Comment by CHEYCKIT** [comment]
> I think 𝕃 is a good idea yeah ! Does it works well for dev side by using this one ? True it should be compatible for builders first, you're right

It's ok, but θ works wayy better in our dapp + It looks like a (pink) pill + it's a Greek letter just like ETH
On X, we could have some reach with :

⟠ for eth
θ for lyx
Take the pill

Or something like that lol

Besides, you wouldn't want folks calling Lukso the "𝕃 Chain" or do "𝕃 + Ratio" etc
If we agree, i'll poll it on X, explaining each side, I hope the community can agree on Theta

**Comment by CHEYCKIT** [comment]
To conclude this, we end up with an two symbols,

[Unicode U+23E3](https://www.compart.com/en/unicode/U+23E3), HTML entity code &#9187
[Unicode U+1D543](https://www.compart.com/en/unicode/U+1D543), HTML entity code &Lopf

![image](https://github.com/lukso-network/LIPs/assets/126706593/925a6216-406b-4ea0-b95d-caf4c5a59dd9)
![image](https://github.com/lukso-network/LIPs/assets/126706593/c5fc38de-0ed1-48b4-8986-916cb7018732)

⏣ is the symbol we should use for LUKSO
𝕃 would be the alternate symbol for LYX

They can be used interchangeably depending on your d-app needs, your format and how zoomed in/out your elements are on your page.
